add (github actions) tests for run-test-forms

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,3 +20,51 @@ jobs:
           curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
       - name: Run tests
         run: roswell/run-fiveam.ros -l ci-utils/test :github-actions-tests :noncoveralls-tests :base-tests
+
+      - name: Run-test-forms tests
+        run: |
+          # put test systems where asdf can find them
+          cp -av t ~/lisp/
+
+          # should fail
+
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-nil)"
+          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-x nil)"
+          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-not-x 123)"
+          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+
+          # should succeed
+
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-t)"
+          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-x 123)"
+          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+
+          roswell/run-test-forms.ros -l ci-utils-test-system "(ci-utils-test-system:return-not-x nil)"
+          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
+
+          # should error
+
+          roswell/run-test-forms.ros -l ci-utils-test-system "(:incomplete-form"
+          if [ $? -eq 2 ] then echo OK else exit 1 fi
+
+          roswell/run-test-forms.ros -l ci-utils-test-system '(error "error!")'
+          if [ $? -eq 2 ] then echo OK else exit 1 fi
+
+          # dependency should error
+          roswell/run-test-forms.ros -l ci-utils-test-system/compile-error "(ci-utils-test-system:return-t)"
+          if [ $? -eq 3 ] then echo OK else exit 1 fi
+
+          roswell/run-test-forms.ros -l ci-utils-test-system/load-error "(ci-utils-test-system:return-t)"
+          if [ $? -eq 3 ] then echo OK else exit 1 fi
+
+          roswell/run-test-forms.ros -l ci-utils-test-system/compile-warn "(ci-utils-test-system:return-t)"
+          if [ $? -eq 3 ] then echo OK else exit 1 fi
+
+          # should succeed?
+          roswell/run-test-forms.ros -l ci-utils-test-system/load-warn "(ci-utils-test-system:return-t)"
+          if [ $? -eq 0 ] then echo OK else exit 1 fi
+
